"""Creación de modelos iniciales

Revision ID: 0e5b4ac648a3
Revises: 
Create Date: 2025-06-11 23:27:04.087291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e5b4ac648a3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asociacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('ciudad', sa.String(), nullable=False),
    sa.Column('pais', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('edad_min', sa.Integer(), nullable=False),
    sa.Column('edad_max', sa.Integer(), nullable=False),
    sa.Column('genero', sa.String(), nullable=False),
    sa.Column('sets_por_partido', sa.Integer(), nullable=False),
    sa.Column('puntos_por_set', sa.Integer(), nullable=False),
    sa.CheckConstraint('edad_min <= edad_max'),
    sa.CheckConstraint('puntos_por_set > 0'),
    sa.CheckConstraint('sets_por_partido > 0'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('torneo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('mesas_disponibles', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jugador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('genero', sa.String(), nullable=False),
    sa.Column('ciudad', sa.String(), nullable=False),
    sa.Column('pais', sa.String(), nullable=False),
    sa.Column('asociacion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asociacion_id'], ['asociacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('torneo_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('horario', sa.DateTime(), nullable=False),
    sa.Column('mesa', sa.Integer(), nullable=False),
    sa.Column('ronda', sa.String(), nullable=True),
    sa.Column('bye', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['torneo_id'], ['torneo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipo_dobles',
    sa.Column('jugador1_id', sa.Integer(), nullable=False),
    sa.Column('jugador2_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['jugador1_id'], ['jugador.id'], ),
    sa.ForeignKeyConstraint(['jugador2_id'], ['jugador.id'], ),
    sa.PrimaryKeyConstraint('jugador1_id', 'jugador2_id')
    )
    op.create_table('inscripcion',
    sa.Column('jugador_id', sa.Integer(), nullable=False),
    sa.Column('torneo_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['jugador_id'], ['jugador.id'], ),
    sa.ForeignKeyConstraint(['torneo_id'], ['torneo.id'], ),
    sa.PrimaryKeyConstraint('jugador_id', 'torneo_id', 'categoria_id')
    )
    op.create_table('resultado_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partido_id', sa.Integer(), nullable=False),
    sa.Column('numero_set', sa.Integer(), nullable=False),
    sa.Column('puntos_jugador1', sa.Integer(), nullable=False),
    sa.Column('puntos_jugador2', sa.Integer(), nullable=False),
    sa.CheckConstraint('puntos_jugador1 >= 0'),
    sa.CheckConstraint('puntos_jugador2 >= 0'),
    sa.ForeignKeyConstraint(['partido_id'], ['partido.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resultado_set')
    op.drop_table('inscripcion')
    op.drop_table('equipo_dobles')
    op.drop_table('partido')
    op.drop_table('jugador')
    op.drop_table('torneo')
    op.drop_table('categoria')
    op.drop_table('asociacion')
    # ### end Alembic commands ###
